//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lead_MGTModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpUser
    {
        public long Id { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public string EmailAddress { get; set; }
        public string EmailConfirmationCode { get; set; }
        public string SaleCode { get; set; }
        public string UserCode { get; set; }
        public Nullable<int> LoaiHopDongId { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public string Name { get; set; }
        public string NormalizedEmailAddress { get; set; }
        public string NormalizedUserName { get; set; }
        public string Password { get; set; }
        public string PasswordResetCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.Guid> ProfilePictureId { get; set; }
        public string SecurityStamp { get; set; }
        public bool ShouldChangePasswordOnNextLogin { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
    }
}
