//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lead_MGTModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD_DieuKienCheckDuAn
    {
        public int Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string TenDieuKien { get; set; }
        public string PhepTinh { get; set; }
        public string GiaTri { get; set; }
        public string Tu { get; set; }
        public string Den { get; set; }
        public Nullable<int> DuAnId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    
        public virtual DA_DuAn DA_DuAn { get; set; }
    }
}
