//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lead_MGTModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DA_DuAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DA_DuAn()
        {
            this.CD_DieuKienCheckDuAn = new HashSet<CD_DieuKienCheckDuAn>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string MaDuAn { get; set; }
        public string TenDuAn { get; set; }
        public System.DateTime NgayPheDuyet { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<int> DoiTacId { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_DieuKienCheckDuAn> CD_DieuKienCheckDuAn { get; set; }
    }
}
