//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Lead_MGTModel.EntityModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LEAD_MGTContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LEAD_MGTContainer object using the connection string found in the 'LEAD_MGTContainer' section of the application configuration file.
        /// </summary>
        public LEAD_MGTContainer() : base("name=LEAD_MGTContainer", "LEAD_MGTContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LEAD_MGTContainer object.
        /// </summary>
        public LEAD_MGTContainer(string connectionString) : base(connectionString, "LEAD_MGTContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LEAD_MGTContainer object.
        /// </summary>
        public LEAD_MGTContainer(EntityConnection connection) : base(connection, "LEAD_MGTContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
