//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lead_MGTModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead_Version
    {
        public long Id { get; set; }
        public Nullable<long> LeadID { get; set; }
        public string Address1 { get; set; }
        public string Band_CC { get; set; }
        public string Band_UPL { get; set; }
        public string Bound_Code { get; set; }
        public Nullable<decimal> CC_Limit { get; set; }
        public Nullable<long> DoiTacId { get; set; }
        public Nullable<long> DuAnID { get; set; }
        public Nullable<int> Created_Id { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Email { get; set; }
        public Nullable<int> Income_Level { get; set; }
        public Nullable<int> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public string Lead_Name { get; set; }
        public string National_Id { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.DateTime> Post_Date { get; set; }
        public string Province { get; set; }
        public string Province_Code { get; set; }
        public string Score_Range { get; set; }
        public Nullable<double> UPL_Interest { get; set; }
        public Nullable<decimal> UPL_Limit { get; set; }
        public Nullable<System.DateTime> Valid_Date { get; set; }
        public string Transfer_To { get; set; }
        public Nullable<System.DateTime> Transfer_Date { get; set; }
        public string District_Code { get; set; }
        public Nullable<int> Process_DuplicateID { get; set; }
        public Nullable<int> Status_DuplicateID { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public string Lead_Code { get; set; }
        public Nullable<long> Lead_GW_Id { get; set; }
    }
}
