//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lead_MGTModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead_Import
    {
        public long Id { get; set; }
        public string Phone_Number { get; set; }
        public string Province_Code { get; set; }
        public string CC_Band { get; set; }
        public Nullable<decimal> CC_Limit { get; set; }
        public Nullable<System.DateTime> Scoring_CC { get; set; }
        public string UPL_Band { get; set; }
        public Nullable<decimal> UPL_Limit { get; set; }
        public string Lai_Suat { get; set; }
        public Nullable<System.DateTime> Scoring_UPL { get; set; }
        public string Bound_Code { get; set; }
        public string San_Pham { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<bool> StatusTransfer { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    }
}
