//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Lead_MGTModel.EntityModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MGT_MODELContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MGT_MODELContainer object using the connection string found in the 'MGT_MODELContainer' section of the application configuration file.
        /// </summary>
        public MGT_MODELContainer() : base("name=MGT_MODELContainer", "MGT_MODELContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MGT_MODELContainer object.
        /// </summary>
        public MGT_MODELContainer(string connectionString) : base(connectionString, "MGT_MODELContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MGT_MODELContainer object.
        /// </summary>
        public MGT_MODELContainer(EntityConnection connection) : base(connection, "MGT_MODELContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
